### ISSUE TITLE
mapbox crash

### ISSUE THREAD

**Issue by gqb** [mapbox/mapbox-plugins-android#1037]
2019-08-16 10:35:26.720 23823-23823/team.opay.pay.alpha A/zygote: runtime.cc:523]   - waiting on <0x01663925> (a okhttp3.ConnectionPool)
2019-08-16 10:35:26.720 23823-23823/team.opay.pay.alpha A/zygote: runtime.cc:523]   at okhttp3.ConnectionPool$1.run(ConnectionPool.java:67)
2019-08-16 10:35:26.720 23823-23823/team.opay.pay.alpha A/zygote: runtime.cc:523]   - locked <0x01663925> (a okhttp3.ConnectionPool)
2019-08-16 10:35:26.721 23823-23823/team.opay.pay.alpha A/zygote: runtime.cc:523] "OkHttp https://api.mapbox.com/..." prio=10 tid=78 Native
2019-08-16 10:35:26.721 23823-23823/team.opay.pay.alpha A/zygote: runtime.cc:523]   at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:73)
2019-08-16 10:35:26.721 23823-23823/team.opay.pay.alpha A/zygote: runtime.cc:523]   at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:246)
2019-08-16 10:35:26.721 23823-23823/team.opay.pay.alpha A/zygote: runtime.cc:523]   at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:166)
2019-08-16 10:35:26.722 23823-23823/team.opay.pay.alpha A/zygote: runtime.cc:523]   at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
2019-08-16 10:35:26.722 23823-23823/team.opay.pay.alpha A/zygote: runtime.cc:523]   at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
2019-08-16 10:35:26.722 23823-23823/team.opay.pay.alpha A/zygote: runtime.cc:523]   at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
2019-08-16 10:35:26.722 23823-23823/team.opay.pay.alpha A/zygote: runtime.cc:523]   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-08-16 10:35:26.722 23823-23823/team.opay.pay.alpha A/zygote: runtime.cc:523]   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-08-16 10:35:26.722 23823-23823/team.opay.pay.alpha A/zygote: runtime.cc:523]   at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
2019-08-16 10:35:26.722 23823-23823/team.opay.pay.alpha A/zygote: runtime.cc:523]   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-08-16 10:35:26.722 23823-23823/team.opay.pay.alpha A/zygote: runtime.cc:523]   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-08-16 10:35:26.722 23823-23823/team.opay.pay.alpha A/zygote: runtime.cc:523]   at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
2019-08-16 10:35:26.722 23823-23823/team.opay.pay.alpha A/zygote: runtime.cc:523]   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-08-16 10:35:26.722 23823-23823/team.opay.pay.alpha A/zygote: runtime.cc:523]   at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
2019-08-16 10:35:26.722 23823-23823/team.opay.pay.alpha A/zygote: runtime.cc:523]   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-08-16 10:35:26.722 23823-23823/team.opay.pay.alpha A/zygote: runtime.cc:523]   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-08-16 10:35:26.722 23823-23823/team.opay.pay.alpha A/zygote: runtime.cc:523]   at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
2019-08-16 10:35:26.722 23823-23823/team.opay.pay.alpha A/zygote: runtime.cc:523]   at okhttp3.RealCall$AsyncCall.execute(RealCall.java:200)
2019-08-16 10:35:26.722 23823-23823/team.opay.pay.alpha A/zygote: runtime.cc:523] "OkHttp Dispatcher" prio=10 tid=79 TimedWaiting
2019-08-16 10:35:26.723 23823-23823/team.opay.pay.alpha A/zygote: runtime.cc:523] "OkHttp https://api.mapbox.com/..." prio=10 tid=85 Native
2019-08-16 10:35:26.724 23823-23823/team.opay.pay.alpha A/zygote: runtime.cc:523]   at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:166)
2019-08-16 10:35:26.724 23823-23823/team.opay.pay.alpha A/zygote: runtime.cc:523]   at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
2019-08-16 10:35:26.724 23823-23823/team.opay.pay.alpha A/zygote: runtime.cc:523]   at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
2019-08-16 10:35:26.724 23823-23823/team.opay.pay.alpha A/zygote: runtime.cc:523]   at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
2019-08-16 10:35:26.724 23823-23823/team.opay.pay.alpha A/zygote: runtime.cc:523]   at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
2019-08-16 10:35:26.724 23823-23823/team.opay.pay.alpha A/zygote: runtime.cc:523]   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-08-16 10:35:26.724 23823-23823/team.opay.pay.alpha A/zygote: runtime.cc:523]   at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
2019-08-16 10:35:26.724 23823-23823/team.opay.pay.alpha A/zygote: runtime.cc:523]   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-08-16 10:35:26.724 23823-23823/team.opay.pay.alpha A/zygote: runtime.cc:523]   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-08-16 10:35:26.724 23823-23823/team.opay.pay.alpha A/zygote: runtime.cc:523]   at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
2019-08-16 10:35:26.724 23823-23823/team.opay.pay.alpha A/zygote: runtime.cc:523]   at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
2019-08-16 10:35:26.724 23823-23823/team.opay.pay.alpha A/zygote: runtime.cc:523]   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-08-16 10:35:26.724 23823-23823/team.opay.pay.alpha A/zygote: runtime.cc:523]   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-08-16 10:35:26.724 23823-23823/team.opay.pay.alpha A/zygote: runtime.cc:523]   at okhttp3.RealCall$AsyncCall.execute(RealCall.java:200)
2019-08-16 10:35:26.724 23823-23823/team.opay.pay.alpha A/zygote: runtime.cc:523]   at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)

**Comment by LukasPaczos** [comment]
Hey @gqb, I don't see any logs related to Mapbox SDKs/plugins in here. Closing as not actionable.
