### ISSUE TITLE
Route Lines when Optimizing a Route

### ISSUE THREAD

**Issue by nitinhemmady** [mapbox/mapbox-plugins-android#1078]
Hi is there a plugin for plotting route lines after route optimization? I did not see support for that. Thanks.

**Comment by langsmith** [comment]
Hi @nitinhemmady , thanks for your interest in Mapbox. 

There's no plugin for this, but our demo app has a complete example of how to draw route lines that come from a Mapbox Optimization API response. This sounds like what you're asking about.

https://docs.mapbox.com/android/java/examples/generate-an-optimized-route/

**Comment by nitinhemmady** [comment]
Hi, I tried building the mapbox demo project and it crashes. Have you experienced this before?

**Comment by langsmith** [comment]
what is the crash message in your log cat?

**Comment by nitinhemmady** [comment]
Is this helpful?

2019-12-12 12:12:13.440 1881-2074/? I/GnssLocationProvider: WakeLock
acquired by sendMessage(REPORT_SV_STATUS, 0,
com.android.server.location.GnssLocationProvider$SvStatusInfo@acdde53)
2019-12-12 12:12:13.441 1881-1894/? I/GnssLocationProvider: WakeLock
released by handleMessage(REPORT_SV_STATUS, 0,
com.android.server.location.GnssLocationProvider$SvStatusInfo@acdde53)
2019-12-12 12:12:14.444 1881-2074/? I/GnssLocationProvider: WakeLock
acquired by sendMessage(REPORT_SV_STATUS, 0,
com.android.server.location.GnssLocationProvider$SvStatusInfo@a972390)
2019-12-12 12:12:14.445 1881-1894/? I/GnssLocationProvider: WakeLock
released by handleMessage(REPORT_SV_STATUS, 0,
com.android.server.location.GnssLocationProvider$SvStatusInfo@a972390)
2019-12-12 12:12:15.087 1881-1959/? W/ActivityManager:   Force finishing
activity com.mapbox.mapboxandroiddemo/.MainActivity
2019-12-12 12:12:15.087 1881-3507/? D/EGL_emulation: eglMakeCurrent:
0xc4abb660: ver 3 0 (tinfo 0xbbaf1120)
2019-12-12 12:12:15.092 1724-1951/? W/SurfaceFlinger: Attempting to destroy
on removed layer: AppWindowToken{c8c5685 token=Token{f5edffc
ActivityRecord{99e58ef u0 com.mapbox.mapboxandroiddemo/.MainActivity
t67}}}#0
2019-12-12 12:12:15.093 1881-3507/? D/OpenGLRenderer: endAllActiveAnimators
on 0xbf929180 (RippleDrawable) with handle 0xca3c78d0
2019-12-12 12:12:15.096 1881-1959/? I/ActivityManager: Killing
21306:com.mapbox.mapboxandroiddemo/u0a97 (adj 900): crash

**Comment by langsmith** [comment]
Unfortunately, the reason is not in those messages. Search for the word `FATAL` in the log.

Does the app even open for you on a real/emulated device? Does it crash when you click on a specific example?

**Comment by nitinhemmady** [comment]
It crashes as soon as I open the app. I cannot see any examples.

**Comment by nitinhemmady** [comment]
Here is what I found:

2019-12-12 12:16:04.081 21354-21354/com.mapbox.mapboxandroiddemo
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.mapboxandroiddemo, PID: 21354
    java.lang.RuntimeException: Unable to instantiate application
com.mapbox.mapboxandroiddemo.MapboxApplication:
java.lang.ClassNotFoundException: Didn't find class
"com.mapbox.mapboxandroiddemo.MapboxApplication" on path: DexPathList[[zip
file
"/data/app/com.mapbox.mapboxandroiddemo-imxFpBePBbdvB4nQUQ7XOg==/base.apk"],nativeLibraryDirectories=[/data/app/com.mapbox.mapboxandroiddemo-imxFpBePBbdvB4nQUQ7XOg==/lib/x86,
/data/app/com.mapbox.mapboxandroiddemo-imxFpBePBbdvB4nQUQ7XOg==/base.apk!/lib/x86,
/system/lib]]
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1069)
        at
android.app.ActivityThread.handleBindApplication(ActivityThread.java:5842)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class
"com.mapbox.mapboxandroiddemo.MapboxApplication" on path: DexPathList[[zip
file
"/data/app/com.mapbox.mapboxandroiddemo-imxFpBePBbdvB4nQUQ7XOg==/base.apk"],nativeLibraryDirectories=[/data/app/com.mapbox.mapboxandroiddemo-imxFpBePBbdvB4nQUQ7XOg==/lib/x86,
/data/app/com.mapbox.mapboxandroiddemo-imxFpBePBbdvB4nQUQ7XOg==/base.apk!/lib/x86,
/system/lib]]
        at
dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at
android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:50)
        at
android.app.Instrumentation.newApplication(Instrumentation.java:1120)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1061)
        at
android.app.ActivityThread.handleBindApplication(ActivityThread.java:5842)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by langsmith** [comment]
Hmm, very strange. Not sure whether you're trying to change the app's code on your local machine to play around with it. If not, you can always just download the app from the Play Store: https://play.google.com/store/apps/details?id=com.mapbox.mapboxandroiddemo&hl=en_US is where you can download it via the Play Store. 

If you still want to install the version from your local machine, here are a couple of things to try:

1. It might not matter in this case, but please make sure that you're trying to install the `globalDebug` flavor: https://github.com/mapbox/mapbox-android-demo#product-flavors

2. I assume you haven't made any changes to the `MapboxApplication`. That correct? If so, use the version that's on `master`. 

3. Try `Build` > `Clean Project` and then `Build` > `Rebuild Project` and then install on the device.

4. Completely uninstall on the device and try re-installing the app.
