### ISSUE TITLE
After add PlacePicker dependency app is not starting

### ISSUE THREAD

**Issue by fraczekkrzysztof** [mapbox/mapbox-plugins-android#1108]
I'd like to use Mapbox PlacePicker plugin for android. My app build.gladle

```
apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'  // Google Services plugin
android {
compileSdkVersion 28
buildToolsVersion "29.0.2"
defaultConfig {
    applicationId "com.fraczekkrzysztof.gocycling"
    minSdkVersion 19
    targetSdkVersion 28
    versionCode 1
    versionName "1.0"
    testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    multiDexEnabled true
}
signingConfigs {
    release {
        storeFile file("C:/AndroidProjects/GoCycling/GoCyclingKey.jks")
        storePassword "kf90pesymista"
        keyAlias "key0"
        keyPassword "kf90pesymista"
    }
}
buildTypes {
    release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        signingConfig signingConfigs.release
    }
}
}
repositories{
 mavenCentral()
}

dependencies {
// Add the Firebase SDK for Google Analytics
implementation 'com.google.firebase:firebase-analytics:17.2.2'
implementation 'com.google.firebase:firebase-auth:19.2.0'
implementation 'com.google.firebase:firebase-ads:18.3.0'
implementation fileTree(dir: 'libs', include: ['*.jar'])
implementation 'androidx.appcompat:appcompat:1.1.0'
implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
testImplementation 'junit:junit:4.12'
androidTestImplementation 'androidx.test.ext:junit:1.1.1'
androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
implementation 'com.android.support:recyclerview-v7:28.0.0'
implementation 'com.loopj.android:android-async-http:1.4.10'
implementation 'com.firebaseui:firebase-ui-auth:6.2.0'
implementation 'com.google.android.material:material:1.1.0'
implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.0.0'
def work_version = "2.3.4"
implementation "androidx.work:work-runtime:$work_version"
implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:9.0.0'
implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-places-v9:0.10.0'
}
```
When I try to run app I received error

```
java.lang.RuntimeException: Unable to get provider com.mapbox.android.telemetry.provider.MapboxTelemetryInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.mapbox.android.telemetry.provider.MapboxTelemetryInitProvider" on path: DexPathList[[zip file "/data/app/com.fraczekkrzysztof.gocycling-NYX_OCILRQtudk9ms3B-kA==/base.apk"],nativeLibraryDirectories=[/data/app/com.fraczekkrzysztof.gocycling-NYX_OCILRQtudk9ms3B-kA==/lib/x86, /data/app/com.fraczekkrzysztof.gocycling-NYX_OCILRQtudk9ms3B-kA==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
    at android.app.ActivityThread.installProvider(ActivityThread.java:6288)
    at android.app.ActivityThread.installContentProviders(ActivityThread.java:5851)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5772)
    at android.app.ActivityThread.-wrap1(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
    at android.os.Handler.dispatchMessage(Handler.java:105)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6541)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
I didn't find solution for PlacePicker. There is some information about similar error in Navigation, but not in PlacePicker. If I removed PlacePicker dependency the app start correctly.

```

**Comment by langsmith** [comment]
Please try the most up-to-date version of the Places Plugin: https://docs.mapbox.com/android/plugins/overview/places/#add-the-dependency

Then cleaned and rebuild the project in Android Studio.

I'd highly also recommend that you invalidate cache + restart in Android Studio as well: [What does the Invalidate Caches/Restart do in Android Studio?](https://stackoverflow.com/questions/31884361/what-does-the-invalidate-caches-restart-do-in-android-studio).

**Comment by langsmith** [comment]
Is it now working for you @fraczekkrzysztof?
