### ISSUE TITLE
Offline plugin: java.lang.IllegalStateException - Missing theme on OfflineActivity

### ISSUE THREAD

**Issue by cohenadair** [mapbox/mapbox-plugins-android#1207]
I received the following crash log from Firebase Crashlytics:
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.cohenadair.anglerslog/com.mapbox.mapboxsdk.plugins.offline.ui.OfflineActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

Environment:
* Android 8.1.0, Nexus 5X
* I'm using the unofficial Flutter plugin: https://github.com/flutter-mapbox-gl
* The Flutter plugin uses:
```
    dependencies {
        implementation "com.mapbox.mapboxsdk:mapbox-android-sdk:9.6.2"
        implementation "com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0"
        implementation "com.mapbox.mapboxsdk:mapbox-android-plugin-localization-v9:0.12.0"
        implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-offline-v9:0.7.0'
    }
```

Notes:
* I'm not quite sure how to reproduce it. I loaded a map on an Android 8 (and 12) emulator while not having an internet connection, and although the map appeared black, the app did not crash.

**Comment by cohenadair** [comment]
Note that this could be related to Google testing devices also causing #712. Will continue to monitor this.
