### ISSUE TITLE
Roboto test crash on LocationLayer

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-plugins-android#122]
Got a random crash on an unrelated CI-build:

```java
FATAL EXCEPTION: ControllerMessenger
Process: com.mapbox.mapboxsdk.plugins.testapp, PID: 19089
com.mapbox.mapboxsdk.style.sources.CannotAddSourceException: Source mapbox-location-source already exists
	at com.mapbox.mapboxsdk.maps.NativeMapView.nativeAddSource(Native Method)
	at com.mapbox.mapboxsdk.maps.NativeMapView.addSource(NativeMapView.java:718)
	at com.mapbox.mapboxsdk.maps.MapboxMap.addSource(MapboxMap.java:433)
	at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayer.addSources(LocationLayer.java:103)
	at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayer.initialize(LocationLayer.java:50)
	at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayer.<init>(LocationLayer.java:44)
	at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin.applyStyle(LocationLayerPlugin.java:196)
	at com.mapbox.mapboxsdk.plugins.testapp.activity.location.LocationLayerMapChangeActivity.onStyleFabClick(LocationLayerMapChangeActivity.java:58)
	at com.mapbox.mapboxsdk.plugins.testapp.activity.location.LocationLayerMapChangeActivity_ViewBinding$1.doClick(LocationLayerMapChangeActivity_ViewBinding.java:39)
	at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
```

it seems that we need to harden this interaction (check before adding if layer already exists, is yes, use that one instead?).

**Comment by tobrun** [comment]
noting that this is probably related to updating the maps sdk to 5.2.0-SNAPSHOT.

**Comment by tobrun** [comment]
Fixed with https://github.com/mapbox/mapbox-plugins-android/pull/142
