### ISSUE TITLE
Location Layer Plugins crashes during recreation if no location was set

### ISSUE THREAD

**Issue by linnar** [mapbox/mapbox-plugins-android#181]
When using LocationLayerPlugin without LocationEngine, if setLocation is never called before destroying activity, Mapbox crashes in mapStyleFinishedLoading during recreation, presumably because previousPoint member is not set.

mapbox android sdk: 5.2.0-beta.4
plugin version: 0.2.0

```
JNI DETECTED ERROR IN APPLICATION: can't call java.lang.String
com.mapbox.services.commons.geojson.GeoJSON.getType() on null object
in call to CallObjectMethodV from void com.mapbox.mapboxsdk.style.sources.GeoJsonSource.nativeSetGeometry(com.mapbox.services.commons.geojson.Geometry)
...
at com.mapbox.mapboxsdk.style.sources.GeoJsonSource.nativeSetGeometry(Native method) 
at com.mapbox.mapboxsdk.style.sources.GeoJsonSource.setGeoJson(GeoJsonSource.java:191)
at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin.mapStyleFinishedLoading(LocationLayerPlugin.java:409)
at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin.onMapChanged(LocationLayerPlugin.java:184)
at com.mapbox.mapboxsdk.maps.MapView.onMapChange(MapView.java:575)
at com.mapbox.mapboxsdk.maps.NativeMapView.onMapChanged(NativeMapView.java:862)
at android.os.MessageQueue.nativePollOnce(Native method)
at android.os.MessageQueue.next(MessageQueue.java:325)
at android.os.Looper.loop(Looper.java:142)
at android.app.ActivityThread.main(ActivityThread.java:6809)
at java.lang.reflect.Method.invoke(Native method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by tobrun** [comment]
Will be fixed with #196
