### ISSUE TITLE
[LocationLayer] crashing issue 

### ISSUE THREAD

**Issue by mf-mindcrewtech** [mapbox/mapbox-plugins-android#223]
I am using locationlayer to show my current location and when I [single/double] tap on map. App getting crashed with following errors. 

NOTE :: My GPS is on and i am getting location.

 java.lang.NullPointerException: Attempt to invoke virtual method 'double android.location.Location.getLatitude()' on a null object reference
                                                                        at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayer.calculateZoomLevelRadius(LocationLayer.java:190)
                                                                        at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayer.updateAccuracyRadius(LocationLayer.java:184)
                                                                        at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin.onCameraMove(LocationLayerPlugin.java:483)

**Comment by davols** [comment]
Can confirm this as well. Running `com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.3.0-SNAPSHOT`

Stacktrace:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'double android.location.Location.getLatitude()' on a null object reference
    at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayer.calculateZoomLevelRadius(LocationLayer.java:190)
    at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayer.updateAccuracyRadius(LocationLayer.java:184)
    at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin.onCameraMove(LocationLayerPlugin.java:483)
    at com.mapbox.mapboxsdk.maps.CameraChangeDispatcher$2.run(CameraChangeDispatcher.java:62)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5539)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by cammace** [comment]
This was an oversight by me, If the locations null, the accuracy is now set to 0 radii. Fix will be in master once https://github.com/mapbox/mapbox-plugins-android/pull/221 is merged.
