### ISSUE TITLE
Npe in TrackingSettings.setOnMyLocationChangeListener(TrackingSettings.java:346) 5.5.0 version

### ISSUE THREAD

**Issue by sibuty** [mapbox/mapbox-plugins-android#379]
Hello.
I use 'my location' from MapView.
When I enabled in android-dev-settings 'dont save state operations', after use home button and restore app, I got this stacktrace:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.mapbox.services.android.telemetry.location.LocationEngine.removeLocationEngineListener(com.mapbox.services.android.telemetry.location.LocationEngineListener)' on a null object reference
                                                                     at com.mapbox.mapboxsdk.maps.TrackingSettings.setOnMyLocationChangeListener(TrackingSettings.java:346)
                                                                     at com.mapbox.mapboxsdk.maps.MapboxMap.setOnMyLocationChangeListener(MapboxMap.java:2130)
```

Sometime later, I found why It has happened.
In TrackingSettings, locationSource do not initialised after restore state, only on create state, look at:
```
MapView initialiseMap method:
if (savedInstanceState == null) {
      mapboxMap.initialise(context, mapboxMapOptions);
    } else {
      mapboxMap.onRestoreInstanceState(savedInstanceState);
    }
```

I fixed it two way:
1) Set MapView in onCreate(state) anytime null mapView.onCreate(null)

2) Use shitty reflection after on create mapbox object:
```
private void checkNpeInTrackingSettings() {
    if(mapboxMap != null) {
      final TrackingSettings trackingSettings = mapboxMap.getTrackingSettings();
      if(trackingSettings != null) {
        final Field[] fields = trackingSettings.getClass().getDeclaredFields();
        for(final Field field : fields) {
          if(LocationEngine.class.isAssignableFrom(field.getType())) {
            field.setAccessible(true);
            try {
              if(field.get(trackingSettings) == null) {
                field.set(trackingSettings, Mapbox.getLocationEngine());
              }
            } catch(final IllegalAccessException e) {
              e.printStackTrace();
            }
            break;
          }
        }
      }
    }
  }
```

How do you think what way is worst?
And mb you can prompt me third way? Or anything else?

**Comment by sibuty** [comment]
Create for mapbox-gl-native.
