### ISSUE TITLE
NPE in TelemetryService

### ISSUE THREAD

**Issue by LouisCAD** [mapbox/mapbox-plugins-android#412]
Happens when I launch my app with these dependencies:
```groovy
// MapBox
    implementation('com.mapbox.mapboxsdk:mapbox-android-sdk:5.5.1') {
        transitive = true
    }
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-cluster-utils:0.1.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.5.0-20180404.141347-46'
    implementation "com.mapbox.mapboxsdk:mapbox-android-plugin-places:0.3.0-20180403.145319-38"
```
Here's the stacktrace:
```stacktrace
NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.getBooleanExtra(java.lang.String, boolean)' on a null object reference
        at com.mapbox.android.telemetry.TelemetryService.enableTelemetryLocationState(TelemetryService.java:203)
        at com.mapbox.android.telemetry.TelemetryService.onStartCommand(TelemetryService.java:48)
```

**Comment by LouisCAD** [comment]
@cammace Why isn't this documented?

**Comment by LouisCAD** [comment]
@cammace It still crashes on SDK 6 anyway, you can reopen the issue.
Here are the updated dependencies:
```groovy
// MapBox
    implementation('com.mapbox.mapboxsdk:mapbox-android-sdk:6.0.0-beta.5') {
        transitive = true
    }
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-cluster-utils:0.1.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.5.0-20180404.141347-46'
    implementation "com.mapbox.mapboxsdk:mapbox-android-plugin-places:0.3.0-20180403.145319-38"
```

**Comment by cammace** [comment]
> Why isn't this documented? Or maybe it is documented at a place I missed?

This is because you are using a snapshot version of the location layer... Our docs only reflect stable releases. 

It's not just the location layer that needs updating, all of the plugins will be updated when the final release of 6.0 occurs. Right now you are also including the Places plugin and Clustering which are using APIs from the 5.x series.
