### ISSUE TITLE
Crash When Clustering Pins on MapBox 6.2.0

### ISSUE THREAD

**Issue by simon-the-canadian** [mapbox/mapbox-plugins-android#563]
I upgraded from 6.1.3 to 6.2.0 and I now get this crash when loading my map with a cluster manager. Also all of my map related code is executed on the main UI thread. 

```
    com.mapbox.mapboxsdk.exceptions.CalledFromWorkerThreadException: Map interactions should happen on the UI thread. Method invoked from wrong thread is .
        at com.mapbox.mapboxsdk.maps.NativeMapView.checkState(NativeMapView.java:104)
        at com.mapbox.mapboxsdk.maps.NativeMapView.getWidth(NativeMapView.java:1094)
        at com.mapbox.mapboxsdk.maps.Projection.getVisibleRegion(Projection.java:96)
        at com.mapbox.mapboxsdk.plugins.cluster.clustering.view.DefaultClusterRenderer$RenderTask.run(DefaultClusterRenderer.java:379)
```

**Comment by simon-the-canadian** [comment]
I updated the plugin to 0.4 but that made no difference.

**Comment by simon-the-canadian** [comment]
@tobrun I'd love to get some feed back on this. I would really like to update to 6.2.0 because of some of the issues on 6.1.3. However all maps that have clusters crash on 6.2.0.

**Comment by simon-the-canadian** [comment]
Wow that's very unfortunate. Seems like clustering would be a common desired feature.

**Comment by mf-mindcrewtech** [comment]
@simon-the-canadian , did you got any workaround solution?

**Comment by simon-the-canadian** [comment]
Yeah, I dropped MapBox and went back to Google Maps. Google just changed its pricing policy on maps so that its free on mobile. Pretty good timing.

**Comment by DavisDevasia** [comment]
I wanted to support both Google Maps and Mapbox because some of the users do not have Google Play services installed on their devices by default.
So I used the changes in https://github.com/mapbox/mapbox-plugins-android/pull/49 to add clustering support for mapbox.

I also faced this error when calling getVisibleRegion.
So I made a workaround:

In class `ViewModifier`
- Modify the constructor to use the main looper
```
public ViewModifier() {
super(Looper.getMainLooper());
}
```

In class `RenderTask`:
- Add a property `mVisibleBounds` and create setter:
```
private LatLngBounds mVisibleBounds;
public void setVisibleBounds(LatLngBounds visibleBounds) {
this.mVisibleBounds = visibleBounds;
}
```
- Replace the call
`final LatLngBounds visibleBounds = mProjection.getVisibleRegion().latLngBounds;` with
`final LatLngBounds visibleBounds = mVisibleBounds;`
- Replace the call
`renderTask.setProjection(projection)` with
`renderTask.setVisibleBounds(projection.getVisibleRegion().latLngBounds);`
- Delete the now useless property `mProjection` and its setter `setProjection` from `RenderTask`

This workaround works because `renderTask.setVisibleBounds` is called by the main looper using the UI thread but everything inside the `RenderTask` is executed by a worker thread.

**Comment by maheshchakkarwar1** [comment]
@DavisDevasia I tried with fix. It working fine.
