### ISSUE TITLE
Location layer plugin crashes while initialising.

### ISSUE THREAD

**Issue by viveksaruk** [mapbox/mapbox-plugins-android#619]
I am initialising location layer plugin as:

private void initLocationLayerPlugin() {
		if (mLocationLayerPlugin == null) {
			mLocationLayerPlugin = new LocationLayerPlugin(mMapView, mMapboxMap, null);
			mLocationLayerPlugin.setLocationLayerEnabled(LocationLayerMode.TRACKING);
		}
	}

Exception is :

Fatal Exception: java.lang.IllegalArgumentException: radius must be > 0
       at android.graphics.RadialGradient.<init>(RadialGradient.java:53)
       at android.graphics.drawable.GradientDrawable.ensureValidRect(GradientDrawable.java:757)
       at android.graphics.drawable.GradientDrawable.draw(GradientDrawable.java:426)
       at android.graphics.drawable.LayerDrawable.draw(LayerDrawable.java:349)
       at com.mapbox.mapboxsdk.plugins.locationlayer.Utils.generateShadow(Utils.java:62)
       at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayer.styleShadow(LocationLayer.java:235)
       at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayer.applyStyle(LocationLayer.java:102)
       at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayer.<init>(LocationLayer.java:83)
       at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin.initialize(LocationLayerPlugin.java:133)
       at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin.<init>(LocationLayerPlugin.java:126)
       at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin.<init>(LocationLayerPlugin.java:97)
       at com.kisanhub.myfarm.MapFragment.initLocationLayerPlugin(MapFragment.java:283)
       at com.kisanhub.myfarm.MapFragment.access$300(MapFragment.java:99)
       at com.kisanhub.myfarm.MapFragment$4.run(MapFragment.java:313)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5341)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by LukasPaczos** [comment]
Hey @viveksaruk, thanks for reaching out. This doesn't seem to be the plugin's issue as looking through `GradientDrawable#ensureValidRect` shows that when `RadialGradient` is created, there will always be a non-zero radius provided
```
if (radius <= 0) {
    // We can't have a shader with non-positive radius, so
    // let's have a very, very small radius.
    radius = 0.001f;
}
mFillPaint.setShader(new RadialGradient(
        x0, y0, radius, gradientColors, null, Shader.TileMode.CLAMP));
```
Looks like the manufacturers implementation is at fault here. I'm closing as not actionable, but could you share which devices did you test on? Also, are you providing a custom shadow drawable?

**Comment by viveksaruk** [comment]
Hey hi @LukasPaczos, Device is Lenovo P70 and operating system is 4.4.4 with 465.00 MiB free ram out of 1.5 GiB.

No I am not providing custom shadow drawable.
