### ISSUE TITLE
Crash offline plugin when cancelling download

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-plugins-android#714]
Click cancel download in the notification when an offline download is ongoing (tap quickly multiple times):

```java
    java.lang.RuntimeException: Unable to start service com.mapbox.mapboxsdk.plugins.offline.offline.OfflineDownloadService@edff33d with Intent { act=com.mapbox.mapboxsdk.plugins.offline.download.cancel flg=0x10000000 cmp=com.mapbox.mapboxsdk.plugins.testapp/com.mapbox.mapboxsdk.plugins.offline.offline.OfflineDownloadService bnds=[1112,688][1392,816] (has extras) }: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.mapboxsdk.offline.OfflineRegion.setDownloadState(int)' on a null object reference
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3694)
        at android.app.ActivityThread.-wrap21(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1801)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.mapboxsdk.offline.OfflineRegion.setDownloadState(int)' on a null object reference
        at com.mapbox.mapboxsdk.plugins.offline.offline.OfflineDownloadService.cancelDownload(OfflineDownloadService.java:177)
        at com.mapbox.mapboxsdk.plugins.offline.offline.OfflineDownloadService.onResolveCommand(OfflineDownloadService.java:111)
        at com.mapbox.mapboxsdk.plugins.offline.offline.OfflineDownloadService.onStartCommand(OfflineDownloadService.java:87)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3677)
        at android.app.ActivityThread.-wrap21(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1801) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6938) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 

```

**Comment by masterjefferson** [comment]
@tobrun I am seeing this problem very frequently with both 0.2.0 and the snapshot.

Also frequently seeing the notification get stuck right when the download should be complete. Happy to help debug, just let me know how I can best assist.

**Comment by arnekaiser** [comment]
>Sometimes pressing cancel doesn't do anything

That's because `OfflineDownloadService.progressDownload()` is updating the notification very often.

**Comment by tobrun** [comment]
no immidiate timeline for that, for now you can test this change with a SNAPSHOT

**Comment by kptlronyttcna** [comment]
This is not fixed. Why closed? I tried the snapshot, still crashes with the same exception. Even when i don't cancel, it crashes. The download never finishes (well it finishes but the notification stays on until it crashes).
