### ISSUE TITLE
LocationLayerPlugin

### ISSUE THREAD

**Issue by matinashtiani** [mapbox/mapbox-plugins-android#784]
Hi recently I had a problem with mapbox. when I'm trying to show user's current location, and using 
`locationPlugin = new LocationLayerPlugin(mapView, mapBoxMap);`

crash occured in LocationLayerPlugin.java:135 and the crash content are as follows:

FATAL EXCEPTION: main
                  Process: com.paklean.android.org, PID: 31540
                  android.content.res.Resources$NotFoundException: Resource ID #0xffffffff
                      at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:225)
                      at android.content.res.Resources.getDrawableForDensity(Resources.java:890)
                      at android.content.res.Resources.getDrawable(Resources.java:833)
                      at android.content.Context.getDrawable(Context.java:605)
                      at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:463)
                      at com.mapbox.mapboxsdk.plugins.locationlayer.Utils.getDrawable(Utils.java:71)
                      at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayer.styleForeground(LocationLayer.java:379)
                      at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayer.applyStyle(LocationLayer.java:127)
                      at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayer.initializeComponents(LocationLayer.java:110)
                      at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayer.<init>(LocationLayer.java:103)
                      at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin.initialize(LocationLayerPlugin.java:686)
              
what should I do? this crash destroyed my app and our user's couldn't open map anymore :|

**Comment by langsmith** [comment]
hey @matinashtiani , thanks for using Mapbox. 

Are you customizing the device location drawable(s) in any way?

I'd **highly** recommend that you switch from the plugin to the `LocationComponent`. The plugin was deprecated a while ago, so further work hasn't been done on it in some time.

Docs about the Maps SDK's `LocationComponent`: https://www.mapbox.com/android-docs/maps/overview/location-component

**Comment by matinashtiani** [comment]
Thanks for your response. I tried to use locationComponent in your tutorial :
 https://www.mapbox.com/android-docs/maps/overview/location-component/  
I exactly used the same code in your example but the user's location didn't show in the map. Can you help me about it?

**Comment by langsmith** [comment]
are you seeing any crashes now that you've switched to the `LocationComponent`, @matinashtiani ?

**Comment by langsmith** [comment]
Conversation has gone stale. Closing for now. More than happy to re-open and continue the conversation if @matinashtiani or others still have issues.
