### ISSUE TITLE
How to draw dashed and standard polyline ?

### ISSUE THREAD

**Issue by ben-j69** [mapbox/mapbox-plugins-android#933]
Hello,

after some research I found the way to draw dashed polyline. I need to set my LineManager as dashed.

But when I try to instantiate a second LineManager to draw normal polylines on my map I get this error :

`com.mapbox.mapboxsdk.style.sources.CannotAddSourceException: Source mapbox-android-line-source already exists
        at com.mapbox.mapboxsdk.maps.NativeMapView.nativeAddSource(Native Method)
        at com.mapbox.mapboxsdk.maps.NativeMapView.addSource(NativeMapView.java:851)
        at com.mapbox.mapboxsdk.maps.Style.addSource(Style.java:103)
        at com.mapbox.mapboxsdk.plugins.annotation.AnnotationManager.initializeSourcesAndLayers(AnnotationManager.java:342)
        at com.mapbox.mapboxsdk.plugins.annotation.AnnotationManager.<init>(AnnotationManager.java:90)
        at com.mapbox.mapboxsdk.plugins.annotation.LineManager.<init>(LineManager.java:98)
        at com.mapbox.mapboxsdk.plugins.annotation.LineManager.<init>(LineManager.java:77)`

I tried to setup LineManager with geoJsonOptions but without success.

So how to properly instantiate two LineManagers on the same map to draw normal and dashed polylines ?

Thanks

**Comment by LukasPaczos** [comment]
Thanks for reaching out @ben-j69! Feature request of instantiating multiple managers is tracked in https://github.com/mapbox/mapbox-plugins-android/issues/921. Closing as a duplicate.

**Comment by ben-j69** [comment]
@LukasPaczos so there is currently no way to draw dashed and not-dashed polyline on the same map ?

**Comment by LukasPaczos** [comment]
Unfortunately, this is correct @ben-j69. This applies to all non-data-driven properties.

**Comment by langsmith** [comment]
@ben-j69 , as @LukasPaczos said, it's not currently possible _with the Annotation Plugin_. You could go the raw source/layer route and add the layers to the map yourself. You can apply dashed styling to one of the `LineLayer`s. There are various demo app examples which style `LineLayer`s: https://github.com/mapbox/mapbox-android-demo

**Comment by ben-j69** [comment]
If some people are searching, this is the correct example : https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/LineLayerActivity.java

**Comment by umeshkanhasoft** [comment]
i want to show arraw line between source and destination and that line above some information how can i do this
