### ISSUE TITLE
Mapbox: Failed to obtain last location update 

### ISSUE THREAD

**Issue by catarinarpds** [mapbox/mapbox-plugins-android#950]
I created an Android App following this tutorial: https://docs.mapbox.com/android/maps/examples/show-a-users-location/

I can open the map but when the app tries to give my current location I'm getting this error:

`D/Mbgl-LocationComponentCompassEngine: Rotation vector sensor not supported on device, falling back to accelerometer and magnetic field.
E/Mbgl-LocationComponent: Failed to obtain last location update
    java.lang.Exception: Last location unavailable
        at com.mapbox.android.core.location.MapboxFusedLocationEngineImpl.getLastLocation(MapboxFusedLocationEngineImpl.java:40)
        at com.mapbox.android.core.location.LocationEngineProxy.getLastLocation(LocationEngineProxy.java:25)
        at com.mapbox.mapboxsdk.location.LocationComponent.setLastLocation(LocationComponent.java:1315)
        at com.mapbox.mapboxsdk.location.LocationComponent.onLocationLayerStart(LocationComponent.java:1134)
        at com.mapbox.mapboxsdk.location.LocationComponent.enableLocationComponent(LocationComponent.java:1248)
        at com.mapbox.mapboxsdk.location.LocationComponent.setLocationComponentEnabled(LocationComponent.java:502)
        at com.example.android.myapplication.MainActivity.enableLocationComponent(MainActivity.java:74)
        at com.example.android.myapplication.MainActivity.access$000(MainActivity.java:25)
        at com.example.android.myapplication.MainActivity$1.onStyleLoaded(MainActivity.java:56)
        at com.mapbox.mapboxsdk.maps.MapboxMap.notifyStyleLoaded(MapboxMap.java:845)
        at com.mapbox.mapboxsdk.maps.MapboxMap.onFinishLoadingStyle(MapboxMap.java:205)
        at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onDidFinishLoadingStyle(MapView.java:1178)
        at com.mapbox.mapboxsdk.maps.MapChangeReceiver.onDidFinishLoadingStyle(MapChangeReceiver.java:194)
        at com.mapbox.mapboxsdk.maps.NativeMapView.onDidFinishLoadingStyle(NativeMapView.java:1040)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:143)
        at android.os.Looper.loop(Looper.java:122)
        at android.app.ActivityThread.main(ActivityThread.java:5930)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
D/SensorManager: registerListener :: 0, K2HH Acceleration , 100000, 0,  
E/SensorManager: sensor or listener is null`

Please help me! Thank you so much. I'm noob so please be kind. *
@mapbox-machine 
@IodaMikeMapbox 
@vikimapbox 
@OulianaMapbox

**Comment by LukasPaczos** [comment]
Hey @catarinarpds, thanks for reaching out!

The only issue I'm seeing here is that you weren't able to obtain a location update. This is just a log, not an actual crash.

Would you be able to provide which version of the Maps SDK have you used and what device have you tested on?

Meanwhile, I'm transferring this issue to out telemetry reposittory.
